# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class ProjectTwo
    def initialize(max)
        @num_1 = 0
        @i = 0
        @sum = 0
        @num_2 = 1
        @max = max
    end

    def even_fibonacci
        while @i <= @max
            @i = @num_1 + @num_2
            @sum += @i if @i % 2 == 0
            @num_1 = @num_2
            @num_2 = @i
        end
        @sum
    end

end

result = ProjectTwo.new(4_000_000)
p result.even_fibonacci
